liip_imagine:
    driver: "gd"

    resolvers:
        default:
            web_path: ~

    filter_sets:
        cache: ~

        admin_post_thumb:
            quality: 75
            filters:
                thumbnail:
                    size: [100, 100]
                    mode: outbound

        visitor_post_thumb:
            quality: 100
            filters:
                thumbnail:
                    size: [300, 300]
                    mode: outbound
