twig:
    file_name_pattern: '*.twig'

    globals:
        cartCounter: '@App\Service\CartCounter'
        settingProvider: '@App\Service\TwigSettingProvider'

when@test:
    twig:
        strict_variables: true